---   
    - name: Install required software packages
      apt:
        name: ['aptitude', 'git']
        state: present
    
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400 #One day
        
    - name: Enable I2C for gpio control
      shell: "raspi-config nonint do_i2c 0"