- name: Setup UPS pimodule on your raspberry pi
  hosts: all
  become: yes
  roles:
    - role: setup
      tags: setup
    - role: pimodule
      tags: pimodule
# Optionally setup the RTC of the UPS PIco HAT
#    - role: pimodule-setup-rtc
#      tags: pimodule-setup-rtc
