# Original project: https://github.com/RomeHein/pimodule
# MIT license
# See instructions at github repo.
# Handler file to reboot when files for configuring the RTC have changed.

---
- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
